### ISSUE TITLE
failing to build the docs: issue with io.BufferedIOBase

### ISSUE THREAD

**Issue by salma1601** [nipy/dipy#1116]
Hi dipy people,

Thanks for sharing such a great tool ! I am new to dipy and diffusion analysis, so I cloned the repo and succeded in running the first examples. However I am failing to build the docs with the `make html` command executed in the `doc` folder. Here is the full traceback

>Traceback (most recent call last):
  File "tools/build_modref_templates.py", line 78, in <module>
    docwriter.write_api_docs(outdir)
  File "/home/salma/CODE/diffusion/dipy/doc/tools/apigen.py", line 473, in write_api_docs
    self.write_modules_api(modules, outdir)
  File "/home/salma/CODE/diffusion/dipy/doc/tools/apigen.py", line 437, in write_modules_api
    head, body = self.generate_api_doc(m)
  File "/home/salma/CODE/diffusion/dipy/doc/tools/apigen.py", line 276, in generate_api_doc
    functions, classes = self._parse_module_with_import(uri)
  File "/home/salma/CODE/diffusion/dipy/doc/tools/apigen.py", line 212, in _parse_module_with_import
    mod = import_module(uri)
  File "/home/salma/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/salma/CODE/diffusion/dipy/dipy/align/imaffine.py", line 55, in <module>
    from dipy.align.imwarp import (get_direction_and_spacings, ScaleSpace)
  File "/home/salma/CODE/diffusion/dipy/dipy/align/imwarp.py", line 9, in <module>
    import nibabel as nib
  File "/home/salma/anaconda2/lib/python2.7/site-packages/nibabel/__init__.py", line 38, in <module>
    from . import analyze as ana
  File "/home/salma/anaconda2/lib/python2.7/site-packages/nibabel/analyze.py", line 87, in <module>
    from .volumeutils import (native_code, swapped_code, make_dt_codes,
  File "/home/salma/anaconda2/lib/python2.7/site-packages/nibabel/volumeutils.py", line 14, in <module>
    import gzip
  File "/home/salma/anaconda2/lib/python2.7/gzip.py", line 36, in <module>
    class GzipFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'
Makefile:38 : la recette pour la cible « api » a échouée
make: *** [api] Erreur 1

**Comment by jchoude** [comment]
This sometimes happen if your ```$PYTHONPATH``` is messed up, for example if something defines an ```io``` module before the system one.

Have a look at your  ```$PYTHONPATH``` by doing:
```
echo $PYTHONPATH
```
and make sure nothing suspicious is present.

**Comment by salma1601** [comment]
You are right ! I had some misfortunate manipulations with `vtk` and added it to my .bashrc `$PYTHONPATH`.
Removing it solved the problem and building is well in place.

Thanks !

**Comment by jchoude** [comment]
Good! Happy that your issue is solved!
