### ISSUE TITLE
Negative integer powers error with numpy 1.12

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#1187]
Testing with numpy 1.12, multiple errors of form:

```
======================================================================
ERROR: dipy.reconst.tests.test_mapmri.test_mapmri_signal_fitting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/dipy/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matthew-brett/dipy/venv/lib/python2.7/site-packages/dipy/reconst/tests/test_mapmri.py", line 184, in test_mapmri_signal_fitting
    anisotropic_scaling=False)
  File "/home/travis/build/matthew-brett/dipy/venv/lib/python2.7/site-packages/dipy/reconst/mapmri.py", line 272, in __init__
    radial_order, 1.)
  File "/home/travis/build/matthew-brett/dipy/venv/lib/python2.7/site-packages/dipy/reconst/mapmri.py", line 1699, in mapmri_isotropic_laplacian_reg_matrix
    gamma(1 / 2.0 + ji + l) / gamma(ji)
ValueError: Integers to negative integer powers are not allowed.
```

https://travis-ci.org/matthew-brett/dipy/jobs/208424940

These are because of a recent change in numpy - see https://docs.scipy.org/doc/numpy/release.html#power-and-raise-errors-for-integer-to-negative-integer-powers

Maybe the calculation should be in floating point rather than integers or something?

**Comment by matthew-brett** [comment]
Cross ref #1186 - where we start to use the latest numpy for tests.

**Comment by arokem** [comment]
I believe this was resolved in https://github.com/nipy/dipy/pull/1186
