### ISSUE TITLE
Improve delimiter on read_bvals_bvecs()

### ISSUE THREAD

**Issue by skoudoro** [nipy/dipy#1417]
## Description

As we can see below, The bvals format (not space delimited?) is not managed. It seems some bvals are space delimited, and some are comma delimited (old ones?), and some TAB delimited.

it should be easy to detect delimiter ([look here](https://stackoverflow.com/a/3952193)) and update [`read_bvals_bvecs()`](https://github.com/nipy/dipy/blob/master/dipy/io/gradients.py#L8)

```
INFO:Computing DTI metrics for ../5a79de2c8e2185002a44906a/59b9ac03620ac10cb3e05d2c/dwi.nii.gz
INFO:Tensor estimation...
Traceback (most recent call last):
  File "/usr/local/bin/dipy_reconst_dti", line 9, in <module>
    run_flow(ReconstDtiFlow())
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/flow_runner.py", line 80, in run_flow
    return flow.run(**args)
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/reconst.py", line 106, in run
    b0_threshold)
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/reconst.py", line 175, in get_fitted_tensor
    bvals, bvecs = read_bvals_bvecs(bval, bvec)
  File "/usr/local/lib/python2.7/dist-packages/dipy/io/gradients.py", line 41, in read_bvals_bvecs
    vals.append(np.squeeze(np.loadtxt(this_fname)))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1024, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 725, in floatconv
    return float(x)
ValueError: invalid literal for float(): 0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000
```

**Comment by nikhilranjan7** [comment]
Hi, Please have a look at my pull request for this issue.

**Comment by abhayjindal51** [comment]
@skoudoro, I have added the csv code to detect delimiter. Can you please share me the test data with which you got this error?
Abhay

**Comment by abhayjindal51** [comment]
@skoudoro I thought this issue was open and I solved it and have submitted a pull request solving the issue. Should I cancel the PR?
Abhay
