### ISSUE TITLE
read_bvals_bvecs crash with bvec rotated eddy

### ISSUE THREAD

**Issue by GuillaumeTh** [nipy/dipy#1449]
## Description
If I use the eddy corrected bvec, I have this error:

```
Traceback (most recent call last):
    File "/home/guillaume/Recherche/Sources/scilpy/scripts/scil_extract_b0.py", line 121, in <module>
      main()
    File "/home/guillaume/Recherche/Sources/scilpy/scripts/scil_extract_b0.py", line 86, in main
      bvals, bvecs = read_bvals_bvecs(args.bvals, args.bvecs)
    File "/home/guillaume/Recherche/Sources/dipy/dipy/io/gradients.py", line 46, in read_bvals_bvecs
      vals.append(np.squeeze(np.loadtxt(this_fname, delimiter=detect_delimiter.delimiter)))
    File "/home/guillaume/Envs/basic_scilpy/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1092, in loadtxt
      for x in read_data(_loadtxt_chunksize):
    File "/home/guillaume/Envs/basic_scilpy/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1019, in read_data
      items = [conv(val) for (conv, val) in zip(converters, vals)]
    File "/home/guillaume/Envs/basic_scilpy/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 738, in floatconv
      return float(x)
  ValueError: could not convert string to float
```
In the bvec rotated file, fsl use double white space. I think the delimiter don't find the double whitespace delimiter. 

If I check the fsl convention (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/UserGuide) the bvec file contains only float and whitespace. The pull request that add delimiter is https://github.com/nipy/dipy/pull/1422.

I think we must only support (one or more) whitespace delimiter.

**Comment by skoudoro** [comment]
hi @GuillaumeTh,

On master branch, we manage multiple delimiters as you can see in PR #1422.

Can you test your file with `master` branch? we plan to release next week so this functionality will be in for DIPY 0.14.0

Let me know if it works correctly with `master` branch.

**Comment by skoudoro** [comment]
Hi @GuillaumeTh, 

Thanks for pointing that. I just created a PR and It should work on #1450
