### ISSUE TITLE
Unexpected behavior in the DIPY workflow script

### ISSUE THREAD

**Issue by parichit** [nipy/dipy#1488]
## Description
The workflow script that extends the base workflow class does not behave as expected always.

The following URL contains the commit of a small test script for DIPY workflows. This script simply checks if the file provided by the user exists in the system or not? However, if the file does not exist then it reports a message (under the else block). 

When the script is run with a valid file path then the output is as expected and it reports the file to be existing. But, when an invalid file path is given then instead of executing the code under the else block it just throws an error-trace. The error trace is expected below:

## Way to reproduce

Note that there is no file named '1' in my system so it should execute the code under the else block.

python check_scratch() /Users/schmuck/Documents/1

Traceback (most recent call last):
  File "check_scratch.py", line 53, in <module>
    run_flow(CheckScratch())
  File "/Users/schmuck/Documents/dipy/dipy/workflows/flow_runner.py", line 82, in run_flow
    return flow.run(**args)
  File "check_scratch.py", line 44, in run
    for fpath in io_it:
  File "/Users/schmuck/Documents/dipy/dipy/workflows/multi_io.py", line 253, in __iter__
    IO = np.concatenate([I, O], axis=1)
ValueError: all the input arrays must have same number of dimensions

**Comment by parichit** [comment]
This is the commit URL to see the script 

https://github.com/parichit/dipy/commit/15cb39d2fac8fd754e39f50fd4a4ad712961f52c

**Comment by parichit** [comment]
Closing the issue to re-try after fixing the PEP8 formatting style in the code.
@skoudoro : Thanks for the pointers.
