### ISSUE TITLE
dipy test failed on mac osx sierra with ananoda python.

### ISSUE THREAD

**Issue by TakafumiYano** [nipy/dipy#1532]
## Description
dipy test failed on mac osx sierra with ananoda python. I installed dipy 0.14 on mac osx with conda command, but it failed to pass the test.

[error log]
FAIL: dipy.viz.tests.test_widgets.test_button_and_slider_widgets
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/dipy/testing/decorators.py", line 68, in test_with_xvfb
    my_test(*args, **kwargs)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/dipy/viz/tests/test_widgets.py", line 123, in test_button_and_slider_widgets
    npt.assert_equal(report.objects, 4)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/numpy/testing/utils.py", line 416, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 6
 DESIRED: 4

FAIL: dipy.viz.tests.test_window.test_order_transparent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/dipy/testing/decorators.py", line 68, in test_with_xvfb
    my_test(*args, **kwargs)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/dipy/viz/tests/test_window.py", line 211, in test_order_transparent
    npt.assert_equal(arr[150, 150][1] > arr[150, 150][0], True)
  File "/Users/takafumi/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/numpy/testing/utils.py", line 416, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: False
 DESIRED: True

----------------------------------------------------------------------
Ran 703 tests in 590.324s

FAILED (SKIP=8, failures=2)
Out[2]: <nose.result.TextTestResult run=703 errors=0 failures=2>

## Way to reproduce
1. installing the anaconda (python 3.6)
2. conda install -c conda-forge dipy
3. conda install vtk
4. ipython
5. import dipy
6. dipy.test()

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#14

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#17
