### ISSUE TITLE
Memory error when running rigid transform

### ISSUE THREAD

**Issue by mattcamp1** [nipy/dipy#1550]
## Description
I'm currently working on a project to run registration on MRIs of the brain.  When attempting to perform a rigid transformation, I continue to get a Memory error even though task manager reports that python is using under 1GB.

Traceback (most recent call last):
  File "C:/Research/Test/test.py", line 51, in <module>
    rigid = affreg.optimize(fixed_data, moving_data, transform, params0, fixed_affine, moving_affine, starting_affine=translation.affine)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dipy\align\imaffine.py", line 1066, in optimize
    options=self.options)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dipy\core\optimize.py", line 230, in __init__
    constraints, tol, callback, options)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\optimize\_minimize.py", line 603, in minimize
    callback=callback, **options)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\optimize\lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\optimize\lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\optimize\optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\optimize\optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dipy\align\imaffine.py", line 750, in distance_and_gradient
    self._update_mutual_information(params, True)
  File "C:\Users\sabin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dipy\align\imaffine.py", line 656, in _update_mutual_information
    grid_to_world)
  File "dipy/align/vector_fields.pyx", line 3438, in dipy.align.vector_fields.gradient (dipy\align\vector_fields.c:132593)
MemoryError

## Way to reproduce
I am following the tutorial on [this site](https://bic-berkeley.github.io/psych-214-fall-2016/dipy_registration.html) to the letter, but with my own MRI data.

OS: Windows-10-10.0.17134-SP0

Python version: Python 3.6.5

DiPy version: 0.14.0

NumPy: 1.14.3
SciPy: 1.1.0
Nibabel: 2.2.1
H5Py: 2.8.0

**Comment by skoudoro** [comment]
Hi @mattcamp1,

> I continue to get a Memory error even though task manager reports that python is using under 1GB

Sounds like a 32 bits python version problem. Can you run this command : `python -c "import sys;print(sys.maxsize > 2**32)`. If it returns `False`, install and try a 64bits version of python

In any case, thanks for reporting this ! What is the size of your data ? How much memory do you have ?

**Comment by mattcamp1** [comment]
That definitely fixed the issue.  I had accidentally installed the 32 bit version of python.

**Comment by skoudoro** [comment]
Great! Thanks for the feedback
