### ISSUE TITLE
PRE is failing :  module 'cvxpy' has no attribute 'utilities'

### ISSUE THREAD

**Issue by skoudoro** [nipy/dipy#1591]
## Description

As you can see [here](https://travis-ci.org/nipy/dipy/jobs/406408052#L6830), `PRE` build is failing on Travis.
 Unfortunately, I can not reproduce this error on my mac or windows machine. I will try to find a linux machine to reproduce this error. It seems that `cvxpy` is not building correctly.

Below, the error: 

```
======================================================================
ERROR: Failure: AttributeError (module 'cvxpy' has no attribute 'utilities')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/dipy/workflows/tests/test_reconst_csa_csd.py", line 12, in <module>
    from dipy.workflows.reconst import ReconstCSDFlow, ReconstCSAFlow
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/dipy/workflows/reconst.py", line 25, in <module>
    from dipy.reconst import mapmri
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/dipy/reconst/mapmri.py", line 22, in <module>
    cvxpy, have_cvxpy, _ = optional_package("cvxpy")
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/dipy/utils/optpkg.py", line 82, in optional_package
    pkg = importlib.import_module(name)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/cvxpy/atoms/geo_mean.py", line 23, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/cvxpy/utilities/power_tools.py", line 21, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/cvxpy/atoms/affine/reshape.py", line 20, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "/home/travis/build/nipy/dipy/venv/lib/python3.5/site-packages/cvxpy/atoms/affine/affine_atom.py", line 21, in <module>
    import cvxpy.utilities as u
AttributeError: module 'cvxpy' has no attribute 'utilities'
```

**Comment by arokem** [comment]
I dare say! Did you report this to the cvxpy developers?

**Comment by skoudoro** [comment]
Not yet, I want to reproduce it first

**Comment by arokem** [comment]
Good find! They should set up a Travis machine to install pre-releases!

**Comment by skoudoro** [comment]
I don't know how, but it seems to be fixed. closing

**Comment by skoudoro** [comment]
it seems that the magic comes from this PR (cvxgrp/cvxpy#558)
