### ISSUE TITLE
Test failure in FORECAST

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1654]
Folllowing up from #1624.

On current master: 

```
dipy (master)$nosetests dipy/reconst/tests/test_forecast.py 
F.....
======================================================================
FAIL: dipy.reconst.tests.test_forecast.test_forecast_positive_constrain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arokem/.virtualenvs/dipy/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/arokem/.virtualenvs/dipy/lib/python3.7/site-packages/numpy/testing/_private/decorators.py", line 155, in skipper_func
    return f(*args, **kwargs)
  File "/Users/arokem/source/dipy/dipy/reconst/tests/test_forecast.py", line 53, in test_forecast_positive_constrain
    assert_almost_equal(fodf[fodf < 0].sum(), 0, 2)
  File "/Users/arokem/.virtualenvs/dipy/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 2 decimals
 ACTUAL: -0.015931951384411995
 DESIRED: 0

----------------------------------------------------------------------
Ran 6 tests in 0.264s

```

Looking closer, it looks like indeed the positivity constraint is no longer applied to the fodf. That is, there are negative components in the fodf. 

My guess is that this has to do with the (very) recent version of cvxpy that was just released today. My hunch is that this is a bug in the way the positivity constraints are implemented in this new version of cvxpy, rather than a change in API. It would be good to come up with a minimal example that we could report to them.

**Comment by skoudoro** [comment]
Can you have a look at this issue https://github.com/cvxgrp/cvxpy/issues/591 @arokem? It seems related to our problem.
