### ISSUE TITLE
Intermittent test failures in `test_streamline`

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1694]
I am working in the `streamline` module (PR to come soon!), and I am getting this kind of test failure appearing every 5 or 6 times I run the test suite for this module:

```
======================================================================
FAIL: dipy.tracking.tests.test_streamline.test_deform_streamlines
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arokem/.virtualenvs/dipy/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/arokem/source/dipy/dipy/tracking/tests/test_streamline.py", line 561, in test_deform_streamlines
    assert_allclose(s, o, rtol=1e-10, atol=0)
  File "/Users/arokem/.virtualenvs/dipy/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1452, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/Users/arokem/.virtualenvs/dipy/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-10, atol=0

(mismatch 100.0%)
 x: array([82.20181 , 91.36506 , 43.15737 , 81.3548  , 96.24868 , 49.895588],
      dtype=float32)
 y: array([132.403147,  91.084219,  42.866592, 153.966459,  95.882702,
        49.858319])

----------------------------------------------------------------------
Ran 18 tests in 5.406s
```

**Comment by skoudoro** [comment]
It is a really long time we did not get this error / weird behavior. Closing! Feel free to reopen it if you see it again
