### ISSUE TITLE
Error using dipy_horizon

### ISSUE THREAD

**Issue by guaje** [nipy/dipy#1756]
## Description

I'm getting the following error using ```dipy_horizon```:

```
Traceback (most recent call last):
  File "/Users/guaj0/.virtualenvs/phd-dipy/bin/dipy_horizon", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/guaj0/Work/PhD/dipy/bin/dipy_horizon", line 10, in <module>
    run_flow(HorizonFlow())
  File "/Users/guaj0/Work/PhD/dipy/dipy/workflows/flow_runner.py", line 91, in run_flow
    return flow.run(**args)
  File "/Users/guaj0/Work/PhD/dipy/dipy/workflows/viz.py", line 87, in run
    out_png=pjoin(out_dir, out_stealth_png))
  File "/Users/guaj0/Work/PhD/dipy/dipy/viz/app.py", line 515, in horizon
    hz.build_show(scene)
  File "/Users/guaj0/Work/PhD/dipy/dipy/viz/app.py", line 224, in build_show
    min_value=lengths.min(),
  File "/Users/guaj0/.virtualenvs/phd-dipy/lib/python3.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
```

Using the following command:

```dipy_horizon --cluster --cluster_thr 5 filename.nii.gz```

I have tried that command on both MacOS and Linux (Ubuntu).

## Way to reproduce
run ```dipy_horizon``` using ```--cluster``` args but use a nifti image instead of a .trk file.

**Comment by skoudoro** [comment]
Thank @guaje for this report

**Comment by Garyfallidis** [comment]
Yes, you need to provide a .trk file as input. And we need to catch the error when you do not have it.
