### ISSUE TITLE
`dipy_fit_csd` CLI is broken?

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1808]
I get this when I run the CLI: 

```
(dipy) dipy_qa (master)$dipy_fit_csd 
Traceback (most recent call last):
  File "/Users/arokem/.virtualenvs/dipy/bin/dipy_fit_csd", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/arokem/source/dipy/bin/dipy_fit_csd", line 9, in <module>
    run_flow(ReconstCSDFlow())
  File "/Users/arokem/source/dipy/dipy/workflows/flow_runner.py", line 32, in run_flow
    sub_flows_dicts = parser.add_workflow(flow)
  File "/Users/arokem/source/dipy/dipy/workflows/base.py", line 151, in add_workflow
    _kwargs['metavar'] = dtype.__name__
AttributeError: 'NoneType' object has no attribute '__name__'
```

Here without inputs, but the same error is raised when the workflow is run with inputs.

**Comment by skoudoro** [comment]
Can you give me your python and dipy version ?

**Comment by arokem** [comment]
I am on current master with Python 3.7:

```
(dipy) dipy_qa (master)$python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dipy
>>> dipy.__version__
'1.0.0dev'
```

**Comment by skoudoro** [comment]
This crash is really strange... It seems to be specific to python3.7 and`dipy_fit_csa` have the same problem.
The investigation starts... Thanks for the report
