### ISSUE TITLE
test_csd_predict test failure on 32-bit linux

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#395]
We're getting a test failure on 32-bit Linux:

```
======================================================================
FAIL: dipy.reconst.tests.test_csdeconv.test_csd_predict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildslave/bongoslave/dipy-py2_6-32/build/venv/local/lib/python2.7/site-packages/dipy/reconst/tests/test_csdeconv.py", line 275, in test_csd_predict
    npt.assert_equal(prediction, model_prediction)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 81.5384615385%)
 x: array([ 1.        ,  0.70275715,  0.46268963,  0.32053749,  0.57845548,
        0.57805053,  0.67724349,  0.57222631,  0.39972592,  0.64854913,
        0.46517094,  0.38457926,  0.37907092,  0.59071299,  0.44852682,...
 y: array([ 1.        ,  0.70275715,  0.46268963,  0.32053749,  0.57845548,
        0.57805053,  0.67724349,  0.57222631,  0.39972592,  0.64854913,
        0.46517094,  0.38457926,  0.37907092,  0.59071299,  0.44852682,...
```

It looks like this failure happened after commit 8019449 and before / at commit c835360

http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/340
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/341

I can't see that the diff explains that, it seems to be text in an example.  Maybe it's some change on the Ubuntu system we're testing on.  Does anyone have any insight as to what's going on here?  Please let me know if you'd like to log in and run on the test machine.

**Comment by arokem** [comment]
Indeed it did. Closed through #396
