### ISSUE TITLE
SPARC buildbot fail in multiprocessing test

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#532]
This one for @yarikoptic I think.

The SPARC buildbot tests are failing for one multiprocessing test : 

http://nipy.bic.berkeley.edu/builders/dipy-py2.7-wheezy-sparc/builds/92/steps/shell_6/logs/stdio

The error is:

```
======================================================================
ERROR: dipy.reconst.tests.test_peaks.test_peaksFromModelParallel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/nd-bb-slave-sparc64-wheezy/dipy-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildslave/nd-bb-slave-sparc64-wheezy/dipy-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/dipy/reconst/tests/test_peaks.py", line 481, in test_peaksFromModelParallel
    return_sh=True, parallel=True)
  File "/home/buildslave/nd-bb-slave-sparc64-wheezy/dipy-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/dipy/reconst/peaks.py", line 409, in peaks_from_model
    nbr_processes)
  File "/home/buildslave/nd-bb-slave-sparc64-wheezy/dipy-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/dipy/reconst/peaks.py", line 200, in _peaks_from_model_parallel
    pool = Pool(nbr_processes)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 138, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 233, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 90] Function not implemented
```

Some searching came up with some mount point suggestions - e.g. http://stackoverflow.com/questions/3314031/django-celery-implementation-oserror-errno-38-function-not-implemented#comment7543003_3699231 .  Is it possible there is something non-standard about the Debian mounts on the SPARC buildbot?

**Comment by yarikoptic** [comment]
I thought I have replied... I guess github ate that reply via email... problem was indeed in lack of mounted shm on that "new" box chroots and it was resolved
