### ISSUE TITLE
OSX test fail 'we check the default value of lambda ...'

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#611]
Anyone recognize this one?

```
======================================================================
FAIL: We check that the default value of lambda is the expected value with
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/MacPython/dipy-wheels/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/travis/build/MacPython/dipy-wheels/venv/lib/python2.7/site-packages/dipy/reconst/tests/test_csdeconv.py", line 454, in test_default_lambda_csdmodel
    npt.assert_array_almost_equal(model_full.B_reg, expected * B_reg)
  File "/Users/travis/build/MacPython/dipy-wheels/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 800, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/Users/travis/build/MacPython/dipy-wheels/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
(mismatch 23.9533456108%)
 x: array([[  2.32929569e+01,   0.00000000e+00,  -0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.32929569e+01,  -1.22849454e+00,  -5.02810375e+00, ...,...
 y: array([[  2.32929581e+01,   0.00000000e+00,  -0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.32929581e+01,  -1.22849461e+00,  -5.02810401e+00, ...,...
```

https://travis-ci.org/MacPython/dipy-wheels/jobs/55117917#L1270

**Comment by arokem** [comment]
Interesting. I see this on python 3.4, but not 2.7, on my (mac) laptop.
Seems to go away with increased precision (#612), but maybe this is the
canary in the coal-mine?

This is not our nipy/dipy travis configuration, right? How/where are you
running this?

**Comment by arokem** [comment]
This one was resolved in https://github.com/nipy/dipy/pull/612
