### ISSUE TITLE
dipy/align/mattes.pyx doctest import error

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#662]
Doctest failure on several buildbots:

```
======================================================================
FAIL: Doctest: dipy.align.mattes.__test__.sample_domain_regular (line 1288)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python33\Lib\doctest.py", line 2179, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for dipy.align.mattes.__test__.sample_domain_regular (line 1288)
  File "c:\buildslaves\win7-32-mini\dipy-bdist32-33\build\venv\lib\site-packages\dipy-0.10.0.dev0-py3.3-win32.egg\dipy\align\mattes.pyd", line unknown line number, in sample_domain_regular (line 1288)

----------------------------------------------------------------------
File "c:\buildslaves\win7-32-mini\dipy-bdist32-33\build\venv\lib\site-packages\dipy-0.10.0.dev0-py3.3-win32.egg\dipy\align\mattes.pyd", line ?, in dipy.align.mattes.__test__.sample_domain_regular (line 1288)
Failed example:
    from dipy.align.mattes import sample_domain_2d_regular
Exception raised:
    Traceback (most recent call last):
      File "c:\Python33\Lib\doctest.py", line 1313, in __run
        compileflags, 1), test.globs)
      File "<doctest dipy.align.mattes.__test__.sample_domain_regular (line 1288)[0]>", line 1, in <module>
        from dipy.align.mattes import `
    ImportError: cannot import name sample_domain_2d_regular
```

http://nipy.bic.berkeley.edu/builders/dipy-bdist32-33/builds/129/steps/shell_8/logs/stdio

I think the import error is correct, there doesn't seem to be any such function `sample_domain_2d_regular` .  Could this be a leftover from some renaming?

**Comment by skoudoro** [comment]
closing. This file do not exist anymore and doctest pass.
