### ISSUE TITLE
dipy.reconst.tests.test_shm.test_sf_to_sh: TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint16') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by ignatenkobrain** [nipy/dipy#755]
```python
======================================================================
ERROR: dipy.reconst.tests.test_shm.test_sf_to_sh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/dipy-0.9.2/build/lib.linux-x86_64-2.7/dipy/reconst/tests/test_shm.py", line 356, in test_sf_to_sh
    sphere = hemi_icosahedron.subdivide(2)
  File "/builddir/build/BUILD/dipy-0.9.2/build/lib.linux-x86_64-2.7/dipy/core/sphere.py", line 369, in subdivide
    sphere = self.mirror()
  File "/builddir/build/BUILD/dipy-0.9.2/build/lib.linux-x86_64-2.7/dipy/core/sphere.py", line 350, in mirror
    _switch_vertex(edges[:,0], edges[:,1], vertices)
  File "/builddir/build/BUILD/dipy-0.9.2/build/lib.linux-x86_64-2.7/dipy/core/sphere.py", line 404, in _switch_vertex
    index2[is_far] += n/2
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint16') with casting rule 'same_kind'
```

**Comment by arokem** [comment]
I believe this was fixed in https://github.com/nipy/dipy/pull/731

Could you please confirm?

**Comment by ignatenkobrain** [comment]
Thanks. It fixes!
