### ISSUE TITLE
Wrong input type for `_voxel2stream` on 64-bit Windows

### ISSUE THREAD

**Issue by matthew-brett** [nipy/dipy#810]
We're getting several errors of form:

```
======================================================================
ERROR: dipy.tracking.tests.test_life.test_voxel2streamline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\buildslaves\mike-win7-64\dipy-bdist64-35\build\venv\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\buildslaves\mike-win7-64\dipy-bdist64-35\build\venv\lib\site-packages\dipy\tracking\tests\test_life.py", line 89, in test_voxel2streamline
    v2f, v2fn = life.voxel2streamline(streamline, False, affine)
  File "C:\buildslaves\mike-win7-64\dipy-bdist64-35\build\venv\lib\site-packages\dipy\tracking\life.py", line 313, in voxel2streamline
    return _voxel2streamline(transformed_streamline, unique_idx)
  File "dipy\tracking\vox2track.pyx", line 20, in dipy.tracking.vox2track._voxel2streamline (dipy\tracking\vox2track.c:1562)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'
```

In fact, `long` and `int` on Windows 64 are length 4 integers.

Here's the relevant part of `voxel2streamline`:

```
    if unique_idx is None:
        all_coords = np.concatenate(transformed_streamline)
        unique_idx = unique_rows(all_coords.astype(int))
    else:
        unique_idx = unique_idx

    return _voxel2streamline(transformed_streamline, unique_idx)
```

So, an obvious fix would be to cast `unique_idx` to `np.intp`, but - is the previous cast to `int` a good idea?  Shouldn't it be `round` instead?

**Comment by arokem** [comment]
I am still thinking about this, but the best solution might actually be in the direction of #811
