### ISSUE TITLE
Compiling the website needs too much memory

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#906]
which is unexpected. 

I had some memory issues compiling the examples. For some reason the examples need more memory than expected. I am on a machine with 16GBytes and I had to close the browser to use all available memory to compile the website. We need to check why some of the memory is not freed. Maybe the reason is that some of the examples call other examples and in that way the memory usage goes up quickly or maybe some other reason.

**Comment by Garyfallidis** [comment]
Here is the traceback
```
Traceback (most recent call last):
  File "../tools/make_examples.py", line 122, in <module>
    execfile(script)
  File "probabilistic_fiber_tracking.py", line 102, in <module>
    mask=white_matter, return_sh=True, parallel=True)
  File "/home/eleftherios/Devel/dipy/dipy/direction/peaks.py", line 410, in peaks_from_model
    nbr_processes)
  File "/home/eleftherios/Devel/dipy/dipy/direction/peaks.py", line 201, in _peaks_from_model_parallel
    pool = Pool(nbr_processes)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
make: *** [rstexamples-stamp] Error 1

```
